name: Cross-Compile main.c

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/main.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/main.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install ARM GCC cross-compiler
      run: |
        sudo apt-get update
        sudo apt install --yes {gcc,binutils}-arm-linux-gnueabihf

    - name: Cross-Compile
      run: | 
        arm-linux-gnueabihf-gcc --version
        arm-linux-gnueabihf-gcc main.c -o HelloWorldArm.exe
        file HelloWorldArm.exe
