name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .  # Bouw context, de huidige map waarin de Dockerfile zich bevindt
        push: true
        tags: your-docker-username/your-docker-repo:latest  # Vervang dit door jouw Docker Hub gebruikersnaam en repository
