name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Dockerfile
      run: echo -e "FROM python:3.9\nCOPY main.py /app/\nWORKDIR /app/\nCMD [\"python\", \"main.py\"]" > Dockerfile

    - name: Set up QEMU (required for cross-platform builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/mandkf/iot_project:latest .

    - name: Log in to Docker
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_UserName }}
        password: ${{ secrets.DOCKER_Paswoord }}

    - name: Push Docker image to Docker Hub
      run: docker push docker.io/mandkf/iot_project:latest
