name: Build and Package

on:
  push:
    branches:
      - main  # Pas aan indien nodig

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t my_app .

    - name: Package Docker image
      run: docker save my_app | gzip > my_app.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_app
        path: my_app.tar.gz
